module.exports = {
    button: {
        login: "[data-test='login']",
    },

    fields: {
        username: "[data-test='username']",
        password: "[data-test='password'] input",        
        logo: "#layout-menu-logo",
        uniqueCode: "[data-test='codeErrorRequired']"
    },

    menu: {        
        dashboard: '/dashboard',
        url:'/login',
        configuration: '//*[@id="menu_item_configuration"]',
        courtCalender: '//*[@id="menu_item_court_calender"]',
        security: '//*[@id="menu_item_security"]',
        ticketProcessing1 : '//*[@Id="menu_item_ticket_processing_"]',
        offenderProfile: "//*[@id='menu_item_offender_profile']",
        editRequest: "//*[@id='menu_item_edit_requests']",
        voidRequest: "//*[@id='menu_item_cancel/void_requests']",
        ticketEnquiry: "//*[@id='menu_item_ticket_enquiry']",
        parish: '//*[@id="menu_item_parish"]',
        policeRank: '//*[@id="menu_item_police_rank"]',
        speedDetectingDevice: '//*[@id="menu_item_speed_detecting_device"]',
        verdict: '//*[@id="menu_item_verdict"]', 
        warrantType: '//*[@id="menu_item_warrant_type"]',
        zone: '//*[@id="menu_item_zone"]',
        offendertype: '//*[@id="menu_item_offender_type"]',
        actiontype: '//*[@id="menu_item_action_type"]',
        country: '//*[@id="menu_item_country"]',
        event: '//*[@id="menu_item_event_"]',
        courthearingtype: '//*[@id="menu_item_court_hear_type"]',
        driverslicense: '//*[@id="menu_item_drivers_licence_class"]',     
        eventreftype: '//*[@id="menu_item_event_ref_type"]',     
        mechanicaldefecttype: '//*[@id="menu_item_mechanical_defect_type"]',
        organizationcategory: '//*[@id="menu_item_organization_category"]', 
        vehicleColor: '//*[@id="menu_item_vehicle_color"]',
        vehicleMake: '//*[@id="menu_item_vehicle_make"]',
        vehicleType: '//*[@id="menu_item_vehicle_type"]',
        location: '//*[@id="menu_item_location"]', 
        idType: '//*[@id="menu_item_id_type"]',
        offenceType: '//*[@id="menu_item_offence"]',
        organization: '//*[@id="menu_item_organization"]',
        reasonType : '//*[@id="menu_item_reason"]',
        ticketType : '//*[@id="menu_item_ticket_type"]',
        action: '//*[@id="menu_item_action"]',
        courtRuling: '//*[@id="menu_item_court_ruling"]',
        organizationType: '//*[@id="menu_item_organization_type"]',
        organizationLocation: '//*[@id="menu_item_organization_location"]',
        organizationStructure: '//*[@id="menu_item_organization_structure"]',
        groupMaintenance: '//*[@id="menu_item_group_maintenance"]',
        userMaintenance: '//*[@id="menu_item_user_maintenance"]',
        issueEticket1: '//*[@id="menu_item_issue_eticket"]',
        manualTicket1: '//*[@id="menu_item_manual_ticket"]',
        warrantProcessing: "//*[@id='menu_item_warrant_processing']",
        courtProcessing: "//*[@id='menu_item_court_processing']",
        prepareCourtSheet: "//*[@id='menu_item_prepare_court_sheet']",
        printCourtSheet: "//*[@id='menu_item_print_court_sheet']",
        assignNewCourtEnbloc: "//*[@id='menu_item_assign_new_court_date_enbloc']",
        updateTicketDetails: "//*[@id='menu_item_update_ticket_details']",
        updateCourtDetails: "//*[@id='menu_item_update_court_details']",
        courtCommitment: "//*[@id='menu_item_court_commitment']",
        courtAppeal: "//*[@id='menu_item_court_appeal']",
        dLDisqualificationByCourt: "//*[@id='menu_item_dl_disqualification_by_court']",
        receiptofDisqualifiedLicenceByCourt: "//*[@id='menu_item_receipt_of_disqualified_license_by_court']",
        deliverDlToIta: "//*[@id='menu_item_deliver_dl_to_ita']",
        earlyReleaseOfDisqualifiedDriversLicence: "//*[@id='menu_item_early_release_of_disqualified_dl']",
        authorizeEarlyRequest: "//*[@id='menu_item_authorize_early_request']",
        withdrawnCaseList: "//*[@id='menu_item_withdrawn_case_list']",
        suspension: "//*[@id='menu_item_suspension']",
        suspendByPoints: "//*[@id='menu_item_suspend_by_points']",
        itemPrintNoticeOfSuspension: "//*[@id='menu_item_print_notice_of_suspension']",
        surrenderingOfDriversLicense:'//*[@id="menu_item_surrendering_of_driver’s_license"]',
        authorizetheReinstatementOfSuspendedDL:'//*[@id="menu_item_authorize_the_reinstatement_of_suspended_dl"]',
        reissueNoticeToTAJ:'//*[@id="menu_item_reissue_notice_to_taj"]',
        printreissueNoticeToTAJ:'//*[@id="menu_item_print_reissue_notice_to_taj"]',
        reprintreissueNoticeToTAJ:'//*[@id="menu_item_reprint_reissue_notice_to_taj"]',
        removalOfEndorsementOnDriversLicence:'//*[@id="menu_item_removal_of_endorsement_on_driver’s_licence"]',
        itemReversalOfSuspensionAdd:'//*[@id="menu_item_reversal_of_suspension_-_add"]',
        utilities: "//*[@id='menu_item_utilities']",
        apiMaintenance: "//*[@id='menu_item_api_maintenance']",
        emailCorrespondenceMaintenance: "//*[@id='menu_item_email_correspondence_maintenance']",
        emailGroupMaintenance: "//*[@id='menu_item_email_group_maintenance']",
        letterHeadSetup: "//*[@id='menu_item_letter_head_setup']",
        reports: "//*[@id='menu_item_reports']",
        cashiering: "//*[@id='menu_item_cashiering']",
        cashierDailySettlement: "//*[@id='menu_item_cashier_daily_settlement']",
        manualPaymentsReceiptListing: "//*[@id='menu_item_manual_payments_receipt_listing']",
        itemOtcReceiptListing: "//*[@id='menu_item_otc_receipt_listing']",





    }
}
