module.exports = {
    button: {
        login: "[data-test='login']",
    },

    fields: {
        username: "[data-test='username']",
        password: "[data-test='password'] input",        
        logo: "#layout-menu-logo",
        uniqueCode: "[data-test='codeErrorRequired']"
    },

    menu: {        
        dashboard: '/dashboard',
        url:'/login',
        configuration: '//*[@id="menu_item_configuration"]',
        courtCalender: '//*[@id="menu_item_court_calender"]',
        security: '//*[@id="menu_item_security"]',
        ticketProcessing1 : '//*[@Id="menu_item_ticket_processing_"]',
        offenderProfile: "//*[@id='menu_item_offender_profile']",
        editRequest: "//*[@id='menu_item_edit_requests']",
        voidRequest: "//*[@id='menu_item_cancel/void_requests']",
        ticketEnquiry: "//*[@id='menu_item_ticket_enquiry']",
        parish: '//*[@id="menu_item_parish"]',
        policeRank: '//*[@id="menu_item_police_rank"]',
        speedDetectingDevice: '//*[@id="menu_item_speed_detecting_device"]',
        verdict: '//*[@id="menu_item_verdict"]', 
        warrantType: '//*[@id="menu_item_warrant_type"]',
        zone: '//*[@id="menu_item_zone"]',
        offendertype: '//*[@id="menu_item_offender_type"]',
        actiontype: '//*[@id="menu_item_action_type"]',
        country: '//*[@id="menu_item_country"]',
        event: '//*[@id="menu_item_event_"]',
        courthearingtype: '//*[@id="menu_item_court_hear_type"]',
        driverslicense: '//*[@id="menu_item_drivers_licence_class"]',     
        eventreftype: '//*[@id="menu_item_event_ref_type"]',     
        mechanicaldefecttype: '//*[@id="menu_item_mechanical_defect_type"]',
        organizationcategory: '//*[@id="menu_item_organization_category"]', 
        vehicleColor: '//*[@id="menu_item_vehicle_color"]',
        vehicleMake: '//*[@id="menu_item_vehicle_make"]',
        vehicleType: '//*[@id="menu_item_vehicle_type"]',
        location: '//*[@id="menu_item_location"]', 
        idType: '//*[@id="menu_item_id_type"]',
        offenceType: '//*[@id="menu_item_offence"]',
        organization: '//*[@id="menu_item_organization"]',
        reasonType : '//*[@id="menu_item_reason"]',
        ticketType : '//*[@id="menu_item_ticket_type"]',
        action: '//*[@id="menu_item_action"]',
        courtRuling: '//*[@id="menu_item_court_ruling"]',
        organizationType: '//*[@id="menu_item_organization_type"]',
        organizationLocation: '//*[@id="menu_item_organization_location"]',
        organizationStructure: '//*[@id="menu_item_organization_structure"]',
        groupMaintenance: '//*[@id="menu_item_group_maintenance"]',
        userMaintenance: '//*[@id="menu_item_user_maintenance"]',
        issueEticket1: '//*[@id="menu_item_issue_eticket"]',
        manualTicket1: '//*[@id="menu_item_manual_ticket"]',
        warrantProcessing: "//*[@id='menu_item_warrant_processing']",
        courtProcessing: "//*[@id='menu_item_court_processing']",
        prepareCourtSheet: "//*[@id='menu_item_prepare_court_sheet']",
        printCourtSheet: "//*[@id='menu_item_print_court_sheet']",
        assignNewCourtEnbloc: "//*[@id='menu_item_assign_new_court_date_enbloc']",
        updateTicketDetails: "//*[@id='menu_item_update_ticket_details']",
        updateCourtDetails: "//*[@id='menu_item_update_court_details']",
        courtCommitment: "//*[@id='menu_item_court_commitment']",
        courtAppeal: "//*[@id='menu_item_court_appeal']",
        dLDisqualificationByCourt: "//*[@id='menu_item_dl_disqualification_by_court']",
        receiptofDisqualifiedLicenceByCourt: "//*[@id='menu_item_receipt_of_disqualified_license_by_court']",
        deliverDlToIta: "//*[@id='menu_item_deliver_dl_to_ita']",
        earlyReleaseOfDisqualifiedDriversLicence: "//*[@id='menu_item_early_release_of_disqualified_dl']",
        authorizeEarlyRequest: "//*[@id='menu_item_authorize_early_request']",
        withdrawnCaseList: "//*[@id='menu_item_withdrawn_case_list']",
        suspension: "//*[@id='menu_item_suspension']",
        suspendByPoints: "//*[@id='menu_item_suspend_by_points']",
        itemPrintNoticeOfSuspension: "//*[@id='menu_item_print_notice_of_suspension']",
        surrenderingOfDriversLicense:'//*[@id="menu_item_surrendering_of_driver’s_license"]',
        authorizetheReinstatementOfSuspendedDL:'//*[@id="menu_item_authorize_the_reinstatement_of_suspended_dl"]',
        reissueNoticeToTAJ:'//*[@id="menu_item_reissue_notice_to_taj"]',
        printreissueNoticeToTAJ:'//*[@id="menu_item_print_reissue_notice_to_taj"]',
        reprintreissueNoticeToTAJ:'//*[@id="menu_item_reprint_reissue_notice_to_taj"]',
        removalOfEndorsementOnDriversLicence:'//*[@id="menu_item_removal_of_endorsement_on_driver’s_licence"]',
        itemReversalOfSuspensionAdd:'//*[@id="menu_item_reversal_of_suspension_-_add"]',
        utilities: "//*[@id='menu_item_utilities']",
        apiMaintenance: "//*[@id='menu_item_api_maintenance']",
        emailCorrespondenceMaintenance: "//*[@id='menu_item_email_correspondence_maintenance']",
        emailGroupMaintenance: "//*[@id='menu_item_email_group_maintenance']",
        letterHeadSetup: "//*[@id='menu_item_letter_head_setup']",
        systemConfiguration: "//*[@id='menu_item_system_configuration']",
        reports: "//*[@id='menu_item_reports']",
        cashiering: "//*[@id='menu_item_cashiering']",
        cashierDailySettlement: "//*[@id='menu_item_cashier_daily_settlement']",
        manualPaymentsReceiptListing: "//*[@id='menu_item_manual_payments_receipt_listing']",
        itemOtcReceiptListing: "//*[@id='menu_item_otc_receipt_listing']",
        courtProceedings: "//*[@id='menu_item_court_proceedings']",
        appealSubmitted: "//*[@id='menu_item_appeals_submitted']",
        commitmentsIssued: "//*[@id='menu_item_commitments_issued']",
        PoliceListForCourtAppearance: "//*[@id='menu_item_police_list_for_court_appearance']",
        withdrawnCasesReports: "//*[@id='menu_item_withdrawn_cases']",
        menu_item_disqualifications: "//*[@id='menu_item_disqualifications']",
        menuItemDriverLicenceDemeritPoints: "//*[@id='menu_item_driver_licence_demerit_points']",
        menuItemExpungedDemeritPoints: "//*[@id='menu_item_expunged_demerit_points']",
        menuItemOffendersWithDemeritPoints: "//*[@id='menu_item_offenders_with_demerit_points']",
        menuItemSuspensionList: "//*[@id='menu_item_suspension_list']",
        menuItemDisqualifiedDriversLicences: '//*[@id="menu_item_disqualified_driver\'s_licences"]',
        menuItemPayments: '//*[@id="menu_item_payments"]',
        editedPaymentsRepors: '//*[@id="menu_item_edited_payments"]',
        failedPaymentsRepors: '//*[@id="menu_item_failed_payments"]',
        summaryOfPaymentsByCourtRepors: '//*[@id="menu_item_summary_of_payments_by_court"]',
        menu_item_ticket_processing_reports: "//*[@id='menu_item_ticket_processing']",
        menu_item_issued_tickets_reports: "//*[@id='menu_item_issued_tickets']",
        menu_item_offender_Reports: "//*[@id='menu_item_offender']",
        menu_item_tickets_for_offender_Reports: "//*[@id='menu_item_tickets_for_offender']",
        menu_item_traffic_offence_register_Reports: "//*[@id='menu_item_traffic_offence_register']",
        menu_item_outstanding_Tickets_Report: "//*[@id='menu_item_outstanding_tickets']",
        menu_item_Paid_Tickets_Report: "//*[@id='menu_item_paid_tickets']",
        menu_item_summary_of_paid_tickets_by_payment_location: "//*[@id='menu_item_summary_of_paid_tickets_by_payment_location']",
        menu_item_summary_of_tickets_issued_by_offence: "//*[@id='menu_item_summary_of_tickets_issued_by_offence']",
        menu_item_summary_of_tickets_issued_by_parish: "//*[@id='menu_item_summary_of_tickets_issued_by_parish']",
        menu_item_summary_of_tickets_issued_by_police_officer: "//*[@id='menu_item_summary_of_tickets_issued_by_police_officer']",
        menu_item_summary_of_tickets_issued_by_police_station: "//*[@id='menu_item_summary_of_tickets_issued_by_police_station']",
        menu_item_utitlies: "//*[@id='menu_item_utilities']",
        menu_item_event_audit: "//*[@id='menu_item_event_audit']",
        menu_item_user_audit: "//*[@id='menu_item_user_audit']",
        menu_item_void_tickets: "//*[@id='menu_item_void_tickets']",
        menu_item_warrants_Reports: "//*[@id='menu_item_warrants']",
        menu_item_warrants_issued_report: "//*[@id='menu_item_warrants_issued_report']",
        menu_item_warrants_summary_report: "//*[@id='menu_item_warrants_summary_report']",
        paymentProcessing: "//*[@id='menu_item_payment_processing']",
        payment:"//*[@id='menu_item_payment']",
        receiptReprint: "//*[@id='menu_item_receipt_reprint']"



    }
}
