module.exports = {
    organizationLocationname: "Ticket Name1",
    shortDescription: "Ticket Test",
    shortDescription1: "Ticket Edited",
    eticketprefix: "EE",
    eticketlength: "5",
    mark: "Mark 1",
    markEdit: "Mark 2",
    streetNumber: "Street no 7",
    streetName: "Street 1",
    postalLocation: "15",
    poBox: "Box 1",
    city: "Gandhinagar",
    phone1: "1234567890",
    phone2: "9876543210",
    phone3: "9726912854",
    phone4: "9722712854",
    fax: "8529637410",
    emailAddress: "abc@gmail.com",
    emailAddressUpdated: "achavda@argusoft.com",
    description: "Organization Location added",
    descriptionUpdated: "Organization Location updated",
    contactPerson: "User1",
    
}